name: CI/CD for NGINX

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Clonar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configurar Docker
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir la imagen
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_IMAGE }}:latest .

      # Subir la imagen al registro de Docker
      - name: Push Docker image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_IMAGE }}:latest

  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      # Clonar el repositorio para el despliegue
      - name: Checkout repository
        uses: actions/checkout@v3

      # Actualizar y desplegar usando docker-compose
      - name: Pull and Deploy Docker Compose
        run: |
          docker-compose down
          sed -i "s|image:.*|image: ${{ secrets.DOCKER_IMAGE }}:latest|g" docker-compose.yml
          docker-compose up -d
